const picUrl = {
  activtyShare: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/20170904/card_share_4.jpg",
  activtyDetail: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/20170904/compete.jpg",
  activtyBanner: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/20170904/img-banner.png",
  page_workBench: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/jump.jpg",
  page_explainActivty: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/20170904/activtyContent.jpg",
  page_matchInvestorEmpty: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/example.png",
  shareCommon: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/20170904/card_share_2.jpg",
  banner_1: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/packet/packet-banner.jpg",
  banner_2: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/slide_banner_1.jpg",
  banner_3: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/slide_banner_3.jpg",
  banner_4: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/slide_banner_4.jpg",
  banner_5: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/slide_banner_5.jpg",
  banner_jump1: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/packet/packet-detail.jpg",
  banner_jump2: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/click_jump_1.jpg",
  banner_jump3: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/click_jump_3.jpg",
  banner_jump4: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/click_jump_4.jpg",
  banner_jump5: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/click_jump_5.jpg",
  band_identity: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/img-bangding%402x.jpg",
  push_success: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/img-tuisong%402x.jpg",
  project_success: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/img-chuangjian%402x.jpg",
  invest_org: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/img-qianzai.jpg",
  banner_personShop: 'http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/img-bg.jpg',
  banner_organization: 'http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/img-bg%402x.jpg',
  page_discoverProject: 'http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/xiangmu%402x.jpg',
  project_detail_backgroud: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/project-lock.png",
  share_modal: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/tips-share.png",
  projectDetailpotential: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/match-project-list.png",
  projectBac: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/img-lock.png",
  signIndentityCard: 'http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/img-ticket.png',
  loadingGif: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/loading.gif",
  bg_hongbao: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/packet/bg-hongbao.png",
  bg_hongbao2: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/packet/bg-hongbao2.png",
  queding_1: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/packet/btn-queding-n.png",
  shengcheng: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/packet/btn-shengcheng-n.png",
  shengcheng2: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/packet/btn-shengcheng2-n.png",
  zhuanfa: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/packet/btn-zhuanfa-n.png",
  meifaguo: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/packet/img-meifaguo.png",
  tankuang: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/packet/img-tankuang.png",
  packetlist: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/packet/img-packet-list.png",
  packetover: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/packet/img-drawed-over.png",
  sendHB: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/packet/img-give-packets.png",
  open: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/packet/open-packets.png",
  openHover: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/packet/btn-shengcheng-hover.png",
  openHover2: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/packet/btn-shengcheng2-hover.png",
  zhanfaHover: "http://weitianshi-2017.oss-cn-shanghai.aliyuncs.com/image/banner/packet/btn-zhuanfa-hover.png",

}

export {
  picUrl
}